version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: elite
      POSTGRES_PASSWORD: dangerous
      POSTGRES_DB: colonisation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://elite:dangerous@db:5432/colonisation"

volumes:
  pgdata: